USE testprep_platform;

-- Base tables
CREATE TABLE IF NOT EXISTS agencies (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, slug VARCHAR(100) NOT NULL UNIQUE, email VARCHAR(255) NOT NULL, phone VARCHAR(20), city VARCHAR(100), brand_color VARCHAR(10) DEFAULT '#1e40af', logo_initials VARCHAR(5), commission_rate DECIMAL(5,2) DEFAULT 60.00, status ENUM('active','pending','suspended') DEFAULT 'active', lms_api_key VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS users (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, role ENUM('super_admin','partner_admin','student') NOT NULL, agency_id INT, phone VARCHAR(20), lms_user_id VARCHAR(100), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (agency_id) REFERENCES agencies(id) ON DELETE SET NULL);

CREATE TABLE IF NOT EXISTS courses (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, category ENUM('IELTS','PTE','TOEFL','GERMAN','FRENCH','SPOKEN_ENGLISH','OTHER') NOT NULL, description TEXT, price DECIMAL(10,2) NOT NULL, duration_weeks INT DEFAULT 12, lms_course_id VARCHAR(100), is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

CREATE TABLE IF NOT EXISTS enrollments (id INT AUTO_INCREMENT PRIMARY KEY, student_id INT NOT NULL, agency_id INT NOT NULL, course_id INT NOT NULL, fee_paid DECIMAL(10,2) NOT NULL, payment_status ENUM('paid','pending','refunded') DEFAULT 'pending', payment_date DATE, coupon_code VARCHAR(50), discount_amount DECIMAL(10,2) DEFAULT 0, lms_enrolled TINYINT(1) DEFAULT 0, sso_token VARCHAR(512), progress_percent INT DEFAULT 0, status ENUM('active','completed','cancelled','on_hold') DEFAULT 'active', enrolled_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (student_id) REFERENCES users(id), FOREIGN KEY (agency_id) REFERENCES agencies(id), FOREIGN KEY (course_id) REFERENCES courses(id));

CREATE TABLE IF NOT EXISTS payouts (id INT AUTO_INCREMENT PRIMARY KEY, agency_id INT NOT NULL, amount DECIMAL(10,2) NOT NULL, eligible_students INT DEFAULT 0, status ENUM('pending','approved','paid','rejected') DEFAULT 'pending', requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, processed_at TIMESTAMP NULL, admin_note TEXT, FOREIGN KEY (agency_id) REFERENCES agencies(id));

CREATE TABLE IF NOT EXISTS coupons (id INT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(50) NOT NULL UNIQUE, agency_id INT NOT NULL, discount_type ENUM('percentage','fixed') DEFAULT 'percentage', value DECIMAL(10,2) NOT NULL, min_order DECIMAL(10,2) DEFAULT 0, max_uses INT DEFAULT 100, used_count INT DEFAULT 0, expires_at DATE, is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (agency_id) REFERENCES agencies(id));

CREATE TABLE IF NOT EXISTS leads (id INT AUTO_INCREMENT PRIMARY KEY, agency_id INT NOT NULL, name VARCHAR(255) NOT NULL, email VARCHAR(255), phone VARCHAR(20), course_interest VARCHAR(100), status ENUM('new','contacted','demo_done','enrolled','lost') DEFAULT 'new', notes TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (agency_id) REFERENCES agencies(id));

-- Live classes tables
CREATE TABLE IF NOT EXISTS batches (id INT AUTO_INCREMENT PRIMARY KEY, agency_id INT NOT NULL, course_id INT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT, start_date DATE, end_date DATE, max_students INT DEFAULT 20, instructor_name VARCHAR(255), class_time TIME, duration_minutes INT DEFAULT 60, status ENUM('draft','scheduled','active','completed','cancelled') DEFAULT 'scheduled', created_by INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (agency_id) REFERENCES agencies(id), FOREIGN KEY (course_id) REFERENCES courses(id), FOREIGN KEY (created_by) REFERENCES users(id));

CREATE TABLE IF NOT EXISTS batch_enrollments (id INT AUTO_INCREMENT PRIMARY KEY, batch_id INT NOT NULL, student_id INT NOT NULL, enrollment_id INT NOT NULL, joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, status ENUM('active','completed','dropped','expelled') DEFAULT 'active', notes TEXT, FOREIGN KEY (batch_id) REFERENCES batches(id) ON DELETE CASCADE, FOREIGN KEY (student_id) REFERENCES users(id), FOREIGN KEY (enrollment_id) REFERENCES enrollments(id), UNIQUE KEY unique_batch_student (batch_id, student_id));

CREATE TABLE IF NOT EXISTS lessons (id INT AUTO_INCREMENT PRIMARY KEY, course_id INT NOT NULL, batch_id INT, lesson_number INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT, content_type ENUM('video','live_class','quiz','assignment','document') DEFAULT 'video', video_url VARCHAR(500), video_duration_minutes INT DEFAULT 0, linked_live_class_id INT, is_published TINYINT(1) DEFAULT 0, is_mandatory TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (course_id) REFERENCES courses(id), FOREIGN KEY (batch_id) REFERENCES batches(id));

CREATE TABLE IF NOT EXISTS live_classes (id INT AUTO_INCREMENT PRIMARY KEY, batch_id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT, instructor_id INT, scheduled_at DATETIME NOT NULL, duration_minutes INT NOT NULL DEFAULT 60, class_mode ENUM('interactive','broadcast','hybrid') DEFAULT 'interactive', max_participants INT DEFAULT 50, jitsi_room_name VARCHAR(255), jitsi_token VARCHAR(512), access_type ENUM('enrolled','demo','public') DEFAULT 'enrolled', demo_expires_at TIMESTAMP NULL, recording_url VARCHAR(500), status ENUM('scheduled','live','completed','cancelled') DEFAULT 'scheduled', created_by INT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (batch_id) REFERENCES batches(id), FOREIGN KEY (instructor_id) REFERENCES users(id), FOREIGN KEY (created_by) REFERENCES users(id));

CREATE TABLE IF NOT EXISTS class_attendance (id INT AUTO_INCREMENT PRIMARY KEY, live_class_id INT NOT NULL, student_id INT NOT NULL, batch_enrollment_id INT NOT NULL, joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, left_at TIMESTAMP NULL, duration_seconds INT DEFAULT 0, participation_score INT DEFAULT 0, time_percent INT DEFAULT 0, status ENUM('present','partial','absent') DEFAULT 'present', FOREIGN KEY (live_class_id) REFERENCES live_classes(id), FOREIGN KEY (student_id) REFERENCES users(id), FOREIGN KEY (batch_enrollment_id) REFERENCES batch_enrollments(id));

CREATE TABLE IF NOT EXISTS progress_tracking (id INT AUTO_INCREMENT PRIMARY KEY, enrollment_id INT NOT NULL, lesson_id INT, batch_id INT, content_type ENUM('video','live_class','quiz','assignment','document') DEFAULT 'video', status ENUM('not_started','in_progress','completed') DEFAULT 'not_started', watch_duration_seconds INT DEFAULT 0, watch_percent INT DEFAULT 0, started_at TIMESTAMP NULL, completed_at TIMESTAMP NULL, score INT DEFAULT 0, notes TEXT, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY (enrollment_id) REFERENCES enrollments(id), FOREIGN KEY (lesson_id) REFERENCES lessons(id), FOREIGN KEY (batch_id) REFERENCES batches(id));

CREATE TABLE IF NOT EXISTS demo_access_requests (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, phone VARCHAR(20), course_interest VARCHAR(100), agency_id INT, request_source ENUM('website','landing_page','partner_referral') DEFAULT 'website', status ENUM('pending','approved','rejected','expired') DEFAULT 'pending', approved_by INT, approved_at TIMESTAMP NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (agency_id) REFERENCES agencies(id), FOREIGN KEY (approved_by) REFERENCES users(id));

CREATE TABLE IF NOT EXISTS demo_users (id INT AUTO_INCREMENT PRIMARY KEY, demo_request_id INT, user_id INT NOT NULL, demo_batch_id INT, access_type ENUM('live_class','batch_preview','full_access') DEFAULT 'live_class', access_granted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, access_expires_at TIMESTAMP NOT NULL, access_status ENUM('active','expired','revoked') DEFAULT 'active', created_by INT, FOREIGN KEY (demo_request_id) REFERENCES demo_access_requests(id), FOREIGN KEY (user_id) REFERENCES users(id), FOREIGN KEY (demo_batch_id) REFERENCES batches(id), FOREIGN KEY (created_by) REFERENCES users(id));

CREATE TABLE IF NOT EXISTS jitsi_tokens (id INT AUTO_INCREMENT PRIMARY KEY, live_class_id INT NOT NULL, user_id INT NOT NULL, token VARCHAR(512) NOT NULL, role ENUM('moderator','participant') DEFAULT 'participant', is_active TINYINT(1) DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, expires_at TIMESTAMP NULL, FOREIGN KEY (live_class_id) REFERENCES live_classes(id), FOREIGN KEY (user_id) REFERENCES users(id));

-- Seed data
INSERT INTO agencies (name, slug, email, city, brand_color, logo_initials, commission_rate) VALUES ('BrightPath Academy', 'brightpath', 'admin@brightpath.in', 'Mumbai', '#1e40af', 'BP', 60.00), ('GlobalVisa Consultants', 'globalvisa', 'ops@globalvisa.com', 'Delhi', '#0f766e', 'GV', 65.00), ('EduStar Institute', 'edustar', 'info@edustar.co', 'Bangalore', '#7c3aed', 'ES', 55.00);

INSERT INTO courses (title, category, description, price, duration_weeks) VALUES ('IELTS Academic Masterclass', 'IELTS', 'Complete IELTS Academic preparation', 14999, 12), ('PTE Academic Core', 'PTE', 'PTE Academic full preparation', 9999, 10), ('TOEFL Comprehensive Prep', 'TOEFL', 'TOEFL iBT complete preparation', 12499, 12);

INSERT INTO users (name, email, password_hash, role) VALUES ('Super Admin', 'admin@testprep.com', '$2b$10$rQZ9uCw1sGzHvLEa2hA7a.8kDmjDtKXqvzGpRoE0FMnYQ5pSbGVWS', 'super_admin');

INSERT INTO users (name, email, password_hash, role, agency_id) VALUES ('Rajan Mehta', 'admin@brightpath.in', '$2b$10$rQZ9uCw1sGzHvLEa2hA7a.8kDmjDtKXqvzGpRoE0FMnYQ5pSbGVWS', 'partner_admin', 1), ('Sonia Kapoor', 'ops@globalvisa.com', '$2b$10$rQZ9uCw1sGzHvLEa2hA7a.8kDmjDtKXqvzGpRoE0FMnYQ5pSbGVWS', 'partner_admin', 2);

INSERT INTO users (name, email, password_hash, role, agency_id, phone) VALUES ('Priya Sharma', 'priya.sharma@email.com', '$2b$10$rQZ9uCw1sGzHvLEa2hA7a.8kDmjDtKXqvzGpRoE0FMnYQ5pSbGVWS', 'student', 1, '9876001001'), ('Kabir Nair', 'kabir.nair@email.com', '$2b$10$rQZ9uCw1sGzHvLEa2hA7a.8kDmjDtKXqvzGpRoE0FMnYQ5pSbGVWS', 'student', 2, '9765001001');

INSERT INTO enrollments (student_id, agency_id, course_id, fee_paid, payment_status, payment_date, progress_percent, status) VALUES (5, 1, 1, 14999, 'paid', '2024-02-10', 85, 'active'), (6, 2, 3, 12499, 'paid', '2024-03-15', 75, 'active');
